### ISSUE TITLE
Support CakePHP 2.0

### ISSUE THREAD

**Issue by Morpheu5** [torifat/cake-menu_builder#1]
Hi there. Your plugin seems to have saved my life :) I had to restructure it a bit to make it work with 2.0, though it's really just a matter of renaming stuff around. I uploaded it to http://www.morpheu5.net/public/MenuBuilder.tar.bz2 if you want to consider making it a branch.

PS. I had to use the full syntax for the build method because it seems that something has changed in the way you retrieve the menu array:

```
<?php echo $this->MenuBuilder->build('main-menu', array(), $menu['main-menu']) ?>
```

**Comment by torifat** [comment]
Thanks for your feedback :) Recently, I've switched to JAVA form PHP :( But, I'll try to update this plugins in my next weekend. You can contribute too.

**Comment by torifat** [comment]
It looks like someone has already done it - https://github.com/prem-prakash/cake-menu_builder/tree/cakephp2

**Comment by Morpheu5** [comment]
Woah, thank you, missed that.
