### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by parafenil** [torifat/cake-menu_builder#19]
I wanted to ask a question about the plugin for cakephp menu builder. I configured everything correctly by following his guide and menu function without problems, but once I try to set the permissions for the users menu item with the "permsissions" disappears even though the user has permission to view it. Can you help me?. Thank you.

**Comment by MarioMarrufo** [comment]
You are using another permission management like ACL?

**Comment by torifat** [comment]
@parafenil need some more details. And, most probably you are using something that is not compatible with our plugins. Like @Sesshomario mentioned before me.

**Comment by torifat** [comment]
@parafenil I'm closing this issue. Feel free to ask if you still need any assistance.
