### ISSUE TITLE
How to integrate ACL Menu Component?

### ISSUE THREAD

**Issue by onurakman** [torifat/cake-menu_builder#21]
How to integrate ACL Menu Component?

**Comment by notRuslan** [comment]
The same question.
I found in readme "Supports ACL Menu Component by Mark Story",
but didn't found How .

**Comment by torifat** [comment]
Sorry, I don't work with PHP anymore. So, I don't know the current state of it. But, it used to work with it. By **Supports ACL Menu Component by Mark Story** I meant, this plugin uses the same object structure.
