### ISSUE TITLE
partialMatch for /news matches both /news/3 as /news-item/3

### ISSUE THREAD

**Issue by joostdekeijzer** [torifat/cake-menu_builder#22]
I would expect that partialMatch checks whole url-parts (separated by /), so when the url is /news it would match /news/ and /news/3/etc but not /newsitem.

**Comment by joostdekeijzer** [comment]
possible fix: https://github.com/joostdekeijzer/cake-menu_builder/tree/issue-22

**Comment by torifat** [comment]
Can you please send me a pull request?
