### ISSUE TITLE
Permission based setup Doesn't works with Auth.

### ISSUE THREAD

**Issue by notRuslan** [torifat/cake-menu_builder#25]
Hi ,
I found  issue in your code:
var user : `array(
    'id' => '6',
    'username' => 'ruslan',
    'roll_id' => null,
    'group' => 'admin',
    'created' => '2016-02-08 12:24:15',
    'modified' => '0000-00-00 00:00:00'
)
`
in your constructor:
`public $settings = array(
        'activeClass' => 'active',
        'firstClass' => 'first-item',
        'childrenClass' => 'has-children',
        'menuClass' => null,
        'evenOdd' => false,
        'itemFormat' => '<li%s>%s%s</li>',
        'wrapperFormat' => '<ul%s>%s</ul>',
        'wrapperClass' => null,
        'noLinkFormat' => '<a href="#">%s</a>',
        'menuVar' => 'menu',
        'authVar' => 'user',
        'authModel' => 'User',
        'authField' => 'group',
        'indentHtmlOutput' => true,
    );
    if (isset($View->viewVars[$this->settings['authVar']]) &&
            isset($View->viewVars[$this->settings['authVar']][$this->settings['authModel']]) &&
            isset($View->viewVars[$this->settings['authVar']][$this->settings['authModel']][$this->settings['authField']])) {
            $this->_group = $View->viewVars[$this->settings['authVar']][$this->settings['authModel']][$this->settings['authField']];
        }
`
$this->_group  - Always is null;

**Comment by notRuslan** [comment]
It works for me:
`if (isset($View->viewVars[$this->settings['authVar']]) &&
            isset($View->viewVars[$this->settings['authVar']][$this->settings['authField']])) {
            $this->_group = $View->viewVars[$this->settings['authVar']][$this->settings['authField']];
        }`

**Comment by notRuslan** [comment]
Any comments?

**Comment by torifat** [comment]
@notRuslan Sorry, I don't work on PHP now a days. So, if you believe you have found an error. You can add a test and submit a pull request. I will merge it gladly.
