### ISSUE TITLE
Readme alteration

### ISSUE THREAD

**Issue by lilHermit** [torifat/cake-menu_builder#4]
Might be worth adding a section about  Loading the Plugin to the bootstrap.php

CakePlugin::load('MenuBuilder');

if the 

CakePlugin::loadAll(); 

is not used.

**Comment by torifat** [comment]
You can do that, I'l merge. I have switched to Java. So, I don't have any idea about CakePHP 2.0

Thats why, the plugin has issues. I hope someone will move it forward :)
