### ISSUE TITLE
When using named arguments it doesn't set the active class on the elements.

### ISSUE THREAD

**Issue by diego-carrera** [torifat/cake-menu_builder#7]
Let's say you define a route to:

``` php
'url' => array('controller' => 'images', 'action' => 'gallery')
```

But that gallery uses pagination
When going to /images/gallery it sets the active class correctly, but where going to
/images/gallery/page:2 it doesn't

**Comment by torifat** [comment]
Try using `partialMatch` - https://github.com/torifat/cake-menu_builder#other-menu-options
