### ISSUE TITLE
Permissions with Related Role Model

### ISSUE THREAD

**Issue by larry-tx** [torifat/cake-menu_builder#8]
When I try to use 'permissions' => array('admin') or 'permissions' => array('') it doesn't seem to work, The first never displays, even if an admin user is logged in, and the second always displays even though an admin is logged in. I'm guessing that it's because there is no role or group field in the User model. Instead, there is a role_id field to a related Role model in keeping with an ACL configuration. Is there a way to restrict the display of menu items by role in this situation?

I've tried including the following settings for MenuBuilder in AppController:

```
'Menu.MenuBuilder' => array(
                'noLinkFormat' => '<div>%s</div>',
                'authField' => 'role_id',
            ),
```

In this case, I also tried using the role_id numbers as in 'permissions' => array('1', '2', '3') , but that prevents the display of the menu item even though debug shows that the logged in user has 'role_id' => '1' in his $user array.

**Comment by torifat** [comment]
Please check - https://github.com/torifat/cake-menu_builder#default-settings

Use `authVar`, `authModel`, `authField` to get the desired outcome.
