### ISSUE TITLE
Trying to Make noLinkFormat work with jQuery UI Accordion

### ISSUE THREAD

**Issue by larry-tx** [torifat/cake-menu_builder#9]
I'm trying to make the noLinkFormat parameter work with jQuery UI Accordion. Theoretically, I need to surround the non-linking menu entry with something distinguishable to jQuery like <h3></h3> tags. Here's what I tried initially:

   In the helper array:

'Menu.MenuBuilder' => array(
                'noLinkFormat' => '<h3>%s</h3>',
                'authField'    => 'role',
                'authVar'      => 'user',
                'authModel'    => 'Users.User'
            ),

In the menu array itself:

array(
   'title'       => 'Learning Resources',
   'permissions' => array(''),
   'children'    => array(
   array(
      'title'       => 'Collections',
     'url'         => 'admin/collections/index',
        and so

Unfortunately, that produced unclickable "Learning Resources" entry in the menu that looked like this in the source code:

<li class="first-item"><a title="Home" href="/pages/home">Home</a></li>
    <li class="has-children">
        <h3>Learning Resources</h3>
        <ul>

So I changed my menu array to look like this:

array(
   'title'       => 'Learning Resources',
   'url'         => '#',
   'permissions' => array(''),
   'children'    => array(
      array(    and so on

However, cake-menu then totally ignored my noLinkFormat parameter and produced this kind of source code:

<li class="first-item"><a title="Home" href="/pages/home">Home</a></li>
<li class="has-children">
   <a title="Learning Resources" href="#">Learning Resources</a>
      <ul>
    <li class="first-item has-children">

With that, I don't see anything that I can hook jQuery UI accordion onto. Am I missing something? Is there a way to do that? Or to set the parameters to create the kind of hooks that it needs?

**Comment by torifat** [comment]
Can you please tell what you are trying to achieve?

**Comment by larry-tx** [comment]
I'm trying to make the noLinkFormat parameter work with jQuery UI Accordion. That mean that the non-linking elements of the menu array need to be surrounded by a HTML block element, preferably `<h3>`. All of the link elements under a non-linking element need to be surrounded by `<div></div>`. For example:

``````
   ```<h3>Widgets</h3>
    <div>
        <ul>
            <li><a href="/widgets/add">Create Widget</a></li>
            <li><a href="/widgets/index">List Widgets</a></li>
        </ul>
    </div>
    <h3>Foo Bar</h3>
    <div>
        <ul>
            <li><a href="/foo_bar/add">Create Foo Bar</a></li>
            <li><a href="foo_bar/index">List Foo Bars</a></li>
        </ul>
    </div>```
``````

As I'm sure you're aware, the jQuery Accordion widget is a very commonly used component of jQuery. Surely there must be a way to use it with the wonderful cake-menu_builder.
